name: 'Telegram  Notify Simple'
description: 'Sending a Telegram message'
author: 'Nikolay'
branding:
  icon: 'message-circle'
  color: 'green'
on:
  pull_request:
    types: [opened, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: start    
      run: |
         curl -s -X POST https://api.telegram.org/bot"${{ secrets.TELEGRAM_TOKEN }}"/sendMessage -d chat_id="${{ secrets.TELEGRAM_TO }}" -d parse_mode="HTML" -d text="test"
